version: "3.8"

services:
  celery_worker:
    deploy:
      mode: replicated
      replicas: 4 # worker 数量
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "celery", "inspect", "ping", "-A", "app.celery"]
      interval: 30s
      timeout: 10s
      retries: 3
